// Generated by gencpp from file mega_rover_project_pkg/GetDataGUI.msg
// DO NOT EDIT!


#ifndef MEGA_ROVER_PROJECT_PKG_MESSAGE_GETDATAGUI_H
#define MEGA_ROVER_PROJECT_PKG_MESSAGE_GETDATAGUI_H

#include <ros/service_traits.h>


#include <mega_rover_project_pkg/GetDataGUIRequest.h>
#include <mega_rover_project_pkg/GetDataGUIResponse.h>


namespace mega_rover_project_pkg
{

struct GetDataGUI
{

typedef GetDataGUIRequest Request;
typedef GetDataGUIResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDataGUI
} // namespace mega_rover_project_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mega_rover_project_pkg::GetDataGUI > {
  static const char* value()
  {
    return "a4d6ac979e18ace79722eb73f934d137";
  }

  static const char* value(const ::mega_rover_project_pkg::GetDataGUI&) { return value(); }
};

template<>
struct DataType< ::mega_rover_project_pkg::GetDataGUI > {
  static const char* value()
  {
    return "mega_rover_project_pkg/GetDataGUI";
  }

  static const char* value(const ::mega_rover_project_pkg::GetDataGUI&) { return value(); }
};


// service_traits::MD5Sum< ::mega_rover_project_pkg::GetDataGUIRequest> should match
// service_traits::MD5Sum< ::mega_rover_project_pkg::GetDataGUI >
template<>
struct MD5Sum< ::mega_rover_project_pkg::GetDataGUIRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mega_rover_project_pkg::GetDataGUI >::value();
  }
  static const char* value(const ::mega_rover_project_pkg::GetDataGUIRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mega_rover_project_pkg::GetDataGUIRequest> should match
// service_traits::DataType< ::mega_rover_project_pkg::GetDataGUI >
template<>
struct DataType< ::mega_rover_project_pkg::GetDataGUIRequest>
{
  static const char* value()
  {
    return DataType< ::mega_rover_project_pkg::GetDataGUI >::value();
  }
  static const char* value(const ::mega_rover_project_pkg::GetDataGUIRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mega_rover_project_pkg::GetDataGUIResponse> should match
// service_traits::MD5Sum< ::mega_rover_project_pkg::GetDataGUI >
template<>
struct MD5Sum< ::mega_rover_project_pkg::GetDataGUIResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mega_rover_project_pkg::GetDataGUI >::value();
  }
  static const char* value(const ::mega_rover_project_pkg::GetDataGUIResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mega_rover_project_pkg::GetDataGUIResponse> should match
// service_traits::DataType< ::mega_rover_project_pkg::GetDataGUI >
template<>
struct DataType< ::mega_rover_project_pkg::GetDataGUIResponse>
{
  static const char* value()
  {
    return DataType< ::mega_rover_project_pkg::GetDataGUI >::value();
  }
  static const char* value(const ::mega_rover_project_pkg::GetDataGUIResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MEGA_ROVER_PROJECT_PKG_MESSAGE_GETDATAGUI_H
