// Generated by gencpp from file mega_rover_project_pkg/localization_stack.msg
// DO NOT EDIT!


#ifndef MEGA_ROVER_PROJECT_PKG_MESSAGE_LOCALIZATION_STACK_H
#define MEGA_ROVER_PROJECT_PKG_MESSAGE_LOCALIZATION_STACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mega_rover_project_pkg
{
template <class ContainerAllocator>
struct localization_stack_
{
  typedef localization_stack_<ContainerAllocator> Type;

  localization_stack_()
    : num(0)
    , x(0.0)
    , y(0.0)  {
    }
  localization_stack_(const ContainerAllocator& _alloc)
    : num(0)
    , x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef int64_t _num_type;
  _num_type num;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::mega_rover_project_pkg::localization_stack_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mega_rover_project_pkg::localization_stack_<ContainerAllocator> const> ConstPtr;

}; // struct localization_stack_

typedef ::mega_rover_project_pkg::localization_stack_<std::allocator<void> > localization_stack;

typedef boost::shared_ptr< ::mega_rover_project_pkg::localization_stack > localization_stackPtr;
typedef boost::shared_ptr< ::mega_rover_project_pkg::localization_stack const> localization_stackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mega_rover_project_pkg::localization_stack_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mega_rover_project_pkg::localization_stack_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mega_rover_project_pkg::localization_stack_<ContainerAllocator1> & lhs, const ::mega_rover_project_pkg::localization_stack_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mega_rover_project_pkg::localization_stack_<ContainerAllocator1> & lhs, const ::mega_rover_project_pkg::localization_stack_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mega_rover_project_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mega_rover_project_pkg::localization_stack_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mega_rover_project_pkg::localization_stack_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mega_rover_project_pkg::localization_stack_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mega_rover_project_pkg::localization_stack_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mega_rover_project_pkg::localization_stack_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mega_rover_project_pkg::localization_stack_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mega_rover_project_pkg::localization_stack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e13670056d980e4c39c3686f3ee472c";
  }

  static const char* value(const ::mega_rover_project_pkg::localization_stack_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e13670056d980e4ULL;
  static const uint64_t static_value2 = 0xc39c3686f3ee472cULL;
};

template<class ContainerAllocator>
struct DataType< ::mega_rover_project_pkg::localization_stack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mega_rover_project_pkg/localization_stack";
  }

  static const char* value(const ::mega_rover_project_pkg::localization_stack_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mega_rover_project_pkg::localization_stack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 num\n"
"float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::mega_rover_project_pkg::localization_stack_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mega_rover_project_pkg::localization_stack_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct localization_stack_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mega_rover_project_pkg::localization_stack_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mega_rover_project_pkg::localization_stack_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MEGA_ROVER_PROJECT_PKG_MESSAGE_LOCALIZATION_STACK_H
