// Generated by gencpp from file mega_rover_project_pkg/SPI_data.msg
// DO NOT EDIT!


#ifndef MEGA_ROVER_PROJECT_PKG_MESSAGE_SPI_DATA_H
#define MEGA_ROVER_PROJECT_PKG_MESSAGE_SPI_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mega_rover_project_pkg
{
template <class ContainerAllocator>
struct SPI_data_
{
  typedef SPI_data_<ContainerAllocator> Type;

  SPI_data_()
    : SPI_send()
    , SPI_get()  {
    }
  SPI_data_(const ContainerAllocator& _alloc)
    : SPI_send(_alloc)
    , SPI_get(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _SPI_send_type;
  _SPI_send_type SPI_send;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _SPI_get_type;
  _SPI_get_type SPI_get;





  typedef boost::shared_ptr< ::mega_rover_project_pkg::SPI_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mega_rover_project_pkg::SPI_data_<ContainerAllocator> const> ConstPtr;

}; // struct SPI_data_

typedef ::mega_rover_project_pkg::SPI_data_<std::allocator<void> > SPI_data;

typedef boost::shared_ptr< ::mega_rover_project_pkg::SPI_data > SPI_dataPtr;
typedef boost::shared_ptr< ::mega_rover_project_pkg::SPI_data const> SPI_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mega_rover_project_pkg::SPI_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mega_rover_project_pkg::SPI_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mega_rover_project_pkg::SPI_data_<ContainerAllocator1> & lhs, const ::mega_rover_project_pkg::SPI_data_<ContainerAllocator2> & rhs)
{
  return lhs.SPI_send == rhs.SPI_send &&
    lhs.SPI_get == rhs.SPI_get;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mega_rover_project_pkg::SPI_data_<ContainerAllocator1> & lhs, const ::mega_rover_project_pkg::SPI_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mega_rover_project_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mega_rover_project_pkg::SPI_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mega_rover_project_pkg::SPI_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mega_rover_project_pkg::SPI_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mega_rover_project_pkg::SPI_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mega_rover_project_pkg::SPI_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mega_rover_project_pkg::SPI_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mega_rover_project_pkg::SPI_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f9a45316a1e893b5b6f361387ec0a12";
  }

  static const char* value(const ::mega_rover_project_pkg::SPI_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f9a45316a1e893bULL;
  static const uint64_t static_value2 = 0x5b6f361387ec0a12ULL;
};

template<class ContainerAllocator>
struct DataType< ::mega_rover_project_pkg::SPI_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mega_rover_project_pkg/SPI_data";
  }

  static const char* value(const ::mega_rover_project_pkg::SPI_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mega_rover_project_pkg::SPI_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string SPI_send\n"
"string SPI_get\n"
;
  }

  static const char* value(const ::mega_rover_project_pkg::SPI_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mega_rover_project_pkg::SPI_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.SPI_send);
      stream.next(m.SPI_get);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SPI_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mega_rover_project_pkg::SPI_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mega_rover_project_pkg::SPI_data_<ContainerAllocator>& v)
  {
    s << indent << "SPI_send: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.SPI_send);
    s << indent << "SPI_get: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.SPI_get);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MEGA_ROVER_PROJECT_PKG_MESSAGE_SPI_DATA_H
