odom_frame: odom
base_link_frame: base_link
world_frame: odom
frequency: 50

imu0: /imu/data
imu0_config: [false, false, false,  # x, y, z
              true, true, true,    # roll, pitch, yaw
              false, false, false, # x_vel, y_vel, z_vel
              false, false, true,  # roll_vel, pitch_vel, yaw_vel
              false, false, false] # x_accel, y_accel, z_accel
imu0_differential: false
imu0_remove_gravitational_acceleration: true

odom0: /encoder/odom
odom0_config: [true, true, false,   # x, y, z
               false, false, true,  # roll, pitch, yaw
               false, false, false, # x_vel, y_vel, z_vel
               false, false, true,  # roll_vel, pitch_vel, yaw_vel
               false, false, false] # x_accel, y_accel, z_accel