odom_frame: odom
base_link_frame: base_link
world_frame: odom
frequency: 50

imu0: /imu/data
imu0_config: [false, false, false, 
              true, true, true,
              false, false, false,
              false, false, true]
imu0_differential: false
imu0_remove_gravitational_acceleration: true

odom0: /odom/wheel
odom0_config: [true, true, false,
               false, false, true,
               false, false, false,
               false, false, true]
